# Generated by Django 2.2 on 2021-05-08 00:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=20, unique=True)),
                ('quantity', models.IntegerField(max_length=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('date', models.DateTimeField(auto_now=True)),
                ('file_path', models.FileField(upload_to='upload/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('xlsb',))])),
                ('summary', models.CharField(max_length=120)),
            ],
        ),
    ]
